[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0

; 🔴 IMPORTANT
displayconnects = yes


; =====================================================
; ================== USER CRM ==========================
; =====================================================

[crm]
secret = 123456

; droits précis (évite all en prod)
read = system,call,log,verbose,command,agent,user,originate
write = system,call,log,verbose,command,agent,originate


permit = 127.0.0.1/255.255.255.0
permit = 192.168.0.0/255.255.0.0
deny = 0.0.0.0/0
